trigger: none
pr: none

variables:
  - group: 'WS100-PM-DHSV'

resources:
  pipelines:
    - pipeline: UnityServicesTrunk
      project: Titanium
      source: "Unity Services Trunk"
      trigger:
        tags:
          - ReleaseReady

extends:
  template: ../templates/pipeline-v4.yml
  parameters:
    environmentName:                  'WS100-PM-DHSV'
    agentName:                        'WS100-PM-DHSV'
    installerFile:                    'Setup_Unity.msi'
    webAppName:                       'Unity'
    AppName:                          'Unity'
    webAppPool:                       'TitaniumSolutionsDentalAppPool'
    customerPackagesUploadScriptPath: 'C:\Build\CustomerPackages\CustomerPackages\AU\DHSV\Run-UploadPackages.ps1'
    customerPackagesXmlReferencePath: 'C:\Build\CustomerPackages\CustomerPackages\AU\DHSV'
    enableBackupRestore:              false
    enableInsuranceHost:              false
    installScriptPath:                'scripts/WS100-PM-DHSV/Install-Unity.ps1'
    organization:                     'Titanium-Solutions'
    project:                          'Titanium'