trigger: none
pr: none

variables:
  - group: 'WS120-QA-LMU'

resources:
  pipelines:
    - pipeline: SaludServices104_120
      project: Titanium
      source: "Salud Services 104.120"
      trigger:
        tags:
          - ReleaseReady

extends:
  template: ../templates/pipeline-v1.yml
  parameters:
    agentName:                        'WS120-QA-LMU'
    webAppPool:                       'TitaniumSolutionsDentalAppPool'
    updateWebConfigScriptPath:        'scripts/WS120-MI-LMU/Update-WebConfig.ps1'
    customerPackagesUploadScriptPath: 'C:\Build\CustomerPackages\CustomerPackages\USA\LMU\Run-UploadPackages.ps1'
    customerPackagesXmlReferencePath: 'C:\Build\CustomerPackages\CustomerPackages\USA\LMU'
    enableBackupRestore:              false
    installOriginScriptPath:          'scripts/WS120-MI-LMU/Install-Origin.ps1'
    organization:                     'Titanium-Solutions'
    project:                          'Titanium'
    variableGroupId:                  '35'