trigger: none
pr: none

variables:
  - group: 'WSS-QA-MOM'

resources:
  pipelines:
    - pipeline: SaludServices104_122
      project: Titanium
      source: "Salud Services 104.122"
      trigger:
        tags:
          - ReleaseReady
    
    - pipeline: InsuranceHostTrunk  # Alias for the referenced pipeline
      project: Titanium                     # The project where the pipeline exists
      source: "InsuranceHost Trunk"        # The actual pipeline name (quoted because it contains spaces)

extends:
  template: ../templates/pipeline-v2.yml
  parameters:
    environmentName:                  'WSS-QA-MON'
    agentName:                        'WSS-QA-MON'
    poolName:                         'Default'
    installerFile:                    'Setup_Origin.msi'
    webAppName:                       'Origin'
    webAppPool:                       'TitaniumSolutionsDentalAppPool'
    customerPackagesUploadScriptPath: 'C:\Build\CustomerPackages\CustomerPackages\Canada\Montreal\Run-UploadPackages.ps1'
    customerPackagesXmlReferencePath: 'C:\Build\CustomerPackages\CustomerPackages\Canada\Montreal'
    enableBackupRestore:              true
    enableInsuranceHost:              true
    backupDirectory:                  '\\DB2022-04.t.titanium.solutions\Backups\WSS-QA-MON'
    installOriginScriptPath:          'scripts/MONTREAL-QA/Install-Salud.ps1'
    organization:                     'Titanium-Solutions'
    project:                          'Titanium'
    variableGroupId:                  '35'